variables:
  DOCKER_IMAGE_NAME: sholalexandra/simplechatapp
  DOCKER_IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  DOCKER_TLS_CERTDIR: "/certs"

stages:
  - build
  - deploy

build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG

deploy_container:
  stage: deploy
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u "$DOCKERHUB_USERNAME" -p "$DOCKERHUB_TOKEN"
  script:
    - docker pull $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker run -d --name simplechatapp_container -p 3000:3000 $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
    - docker stop simplechatapp_container
    - docker ps -a -q --filter "name=simplechatapp_container" | xargs docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'
    - docker run --name simplechatapp_container -p 3000:3000 $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
